const debtorData = [
    {
      id: "D001",
      name: "John Doe",
      accBalance: "50,000 AED",
      metalWeight: "10 kg",
      goldRateValueInAED: "220 AED/g",
      margin: "5%",
      netEquity: "45,000 AED",
      marginAmount: "2,500 AED",
      totalNeeded: "47,500 AED",
      favorite: true,
    },
    {
      id: "D002",
      name: "Alice Smith",
      accBalance: "75,000 AED",
      metalWeight: "15 kg",
      goldRateValueInAED: "225 AED/g",
      margin: "4%",
      netEquity: "72,000 AED",
      marginAmount: "3,000 AED",
      totalNeeded: "74,000 AED",
      favorite: false,
    },
    {
      id: "D003",
      name: "Michael Johnson",
      accBalance: "30,000 AED",
      metalWeight: "5 kg",
      goldRateValueInAED: "218 AED/g",
      margin: "6%",
      netEquity: "28,000 AED",
      marginAmount: "1,800 AED",
      totalNeeded: "29,800 AED",
      favorite: false,
    },
    {
      id: "D004",
      name: "Sarah Wilson",
      accBalance: "90,000 AED",
      metalWeight: "20 kg",
      goldRateValueInAED: "230 AED/g",
      margin: "3.5%",
      netEquity: "85,000 AED",
      marginAmount: "3,500 AED",
      totalNeeded: "88,500 AED",
      favorite: true,
    },
    {
      id: "D005",
      name: "David Brown",
      accBalance: "60,000 AED",
      metalWeight: "12 kg",
      goldRateValueInAED: "222 AED/g",
      margin: "4.5%",
      netEquity: "57,000 AED",
      marginAmount: "2,700 AED",
      totalNeeded: "59,700 AED",
      favorite: false,
    }
  ];
  
  export default debtorData;
  